### ISSUE TITLE
Add "Rules" for Tic-Tac-Toe

### ISSUE THREAD

**Issue by malivinayak** [malivinayak/Tic-Tac-Toe#3] opened 2023-10-03 10:48 UTC
Description:

The current version of the Tic-Tac-Toe game lacks information about the rules of the game, which is essential for players, especially those who might be new to the game. To improve the user experience and provide clarity on how the game is played, it is recommended to add a "Rules" button to the game interface.

Suggested Enhancement:

- Introduce a "Rules" button at the bottom of the game page.
- When users click on the "Rules" button, a popup should appear with detailed instructions explaining how to play Tic-Tac-Toe, including the rules, winning combinations, which player has which symbol, and how the game is typically conducted.

Expected Behavior:

Players will have easy access to the rules and instructions for the game by clicking the "Rules" button, which will display a popup with the necessary information.

**Comment by malivinayak** [comment] 2023-10-03 11:19
@Sankalp20Tiwari Thank You for your interest.

> I will be highly obliged if you assign this issue to me

You can start working on and make PR.  Once PR is make I will assign this issue to you after review.

> P.S - Please add hacktoberfest-accepted label to this issue.

hacktoberfest-accepted label will only be added to the PR's after review. You can make PR first then we can make further moves after review.

**Comment by tejasviurka** [comment] 2023-10-03 13:19
Can you please elaborate on the issue like We have to make a button which on click shows the rules to play tic-tac-toe or rock-paper-scissor or both.

**Comment by Mouli-3542** [comment] 2023-10-03 14:22
@malivinayak Added rules as an **alert** ...will make a PR if u liked it ....can also do further changes...pls assign this to me
![rules](https://github.com/malivinayak/Tic-Tac-Toe/assets/143725284/ed69353f-379b-4907-953e-50599b95fcde)

**Comment by malivinayak** [comment] 2023-10-03 16:21
> rules to play tic-tac-toe or rock-paper-scissor or both.

@tejasviurka  It should be related to Tic-Tac-Toe. There was typo in description

**Comment by malivinayak** [comment] 2023-10-03 16:28
> Can you please elaborate on the issue

@tejasviurka 
As already mention in description 
- add a "Rules" button to the game interface at the bottom of the game page. (It should be responsive and works on smaller screen too)
- > When users click on the "Rules" button, a popup should appear

   References for pop up
      - [How To Make A Popup - YT VIdeo](https://www.youtube.com/watch?v=AF6vGYIyV8M)
      - [Pure css pop up box - codepen](https://codepen.io/imprakash/full/GgNMXO)
- mention all the information as well as rules about game

**Comment by malivinayak** [comment] 2023-10-03 16:30
> Added rules as an **alert**

@Mouli-3542 
Instead of posting screenshot in issue just make PR next time and link it to the respective issue

I am expecting pop up box instead of alert message
issue is elborated at https://github.com/malivinayak/Tic-Tac-Toe/issues/3#issuecomment-1745329821

**Comment by tejasviurka** [comment] 2023-10-03 17:59
I made the changes that were required. 
I made a Rules button at the bottom of the page, which pops up the Tic Tac Toe Rules.
But the problem is that I'm not able to make PR, I tried for 3 to 4 times.

![Screenshot (92)](https://github.com/malivinayak/Tic-Tac-Toe/assets/113376160/e64a3058-aef0-41ba-8dce-541667621e30)

**Comment by malivinayak** [comment] 2023-10-03 18:04
> But the problem is that I'm not able to make PR, I tried for 3 to 4 times.

I just checked, You have not yet pushed the changes to github repo 
Currently the repo you have forked is up to date with malivinayak/Tic-Tac-Toe:main.

Solution : 
Push the changes to github repo you will able to make PR contribution

**Comment by malivinayak** [comment] 2023-10-03 18:06
> ![Screenshot (92)](https://user-images.githubusercontent.com/113376160/272355771-e64a3058-aef0-41ba-8dce-541667621e30.png)

In rules mention that player 1 is X and player 2 is O
Add some appropriate css to the pop-up

**Comment by tejasviurka** [comment] 2023-10-03 18:11
> > But the problem is that I'm not able to make PR, I tried for 3 to 4 times.
> 
> I just checked, You have not yet pushed the changes to github repo Currently the repo you have forked is up to date with malivinayak/Tic-Tac-Toe:main.
> 
> Solution : Push the changes to github repo you will able to make PR contribution

Yes I am not able to push the changes I made , if you can help me it means a lot

**Comment by malivinayak** [comment] 2023-10-03 18:12
> Yes I am not able to push the changes I made , if you can help me it means a lot

What is the issue exactly. 
Why you are not able to push the changes

**Comment by tejasviurka** [comment] 2023-10-03 18:15
> > Yes I am not able to push the changes I made , if you can help me it means a lot
> 
> What is the issue exactly. Why you are not able to push the changes

![Screenshot 2023-10-03 234616](https://github.com/malivinayak/Tic-Tac-Toe/assets/113376160/b218bd24-a0a5-4c65-b0c2-b43801b401aa)

When I am commiting the changes , they are showing this

**Comment by malivinayak** [comment] 2023-10-03 18:21
I will tell you alteranate way.
On github click on Add files and upload files
upload all the files present in folder i.e. are as follows
![image](https://github.com/malivinayak/Tic-Tac-Toe/assets/66154908/84c0be50-ace8-4fef-a9f0-f7d3e1cb06c2)

and then simply commit

**Comment by malivinayak** [comment] 2023-10-03 18:23
> That's why I am able to commit the changes as well as push it.

I got the issue
You need to open the terminal inside the Tic-Tac-Toe folder

currently terminal is open at home/root folder

**Comment by malivinayak** [comment] 2023-10-03 18:25
@tejasviurka If you join the google meet then I can easily explain, if you are ok with it

[Meet Link](https://meet.google.com/whb-iugx-zdk)

**Comment by malivinayak** [comment] 2023-10-03 18:38
[Link ](https://meet.google.com/whb-iugx-zdk)

**Comment by tejasviurka** [comment] 2023-10-03 18:39
Sorry I guess my network is not good, can you please tell me what i can do to resolve this problem.

**Comment by malivinayak** [comment] 2023-10-03 18:40
You should open the terminal inside the Tic-Tac_toe folder

**Comment by tejasviurka** [comment] 2023-10-03 18:41
Okayyy

**Comment by malivinayak** [comment] 2023-10-03 18:42
At any stage if you feel like you are not getting just attach screenshot here

**Comment by malivinayak** [comment] 2023-10-03 18:52
> can you please tell me what i can do to resolve this problem.

You are uploading the file my creating the new repo which will not able to make PR

**Comment by Sankalp20Tiwari** [comment] 2023-10-03 19:14
Hey @malivinayak I have created the pull request. I want you to take a look at the commit and tell me if i need to make any further chnages.

**Comment by malivinayak** [comment] 2023-10-04 08:15
@tejasviurka Any updates

**Closed as completed** 2023-10-04 10:24 UTC
Labels: enhancement, HACKTOBERFEST
